name: Prettier
on: [push, pull_request]
jobs:
  checkout-install-build:
    name: Checkout, Install, and Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
          version: 10
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
          node-version-file: package.json
      - run: pnpm run build
